# -*- coding: utf-8 -*-
"""The Role of Machine Learning on Phonoloigcal Processes | Behaviorial Sciences | Sean Kim 11th | CVHS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VCGLDmFn-NcAUCMIhPAw3wodjgnWZZa

## **Capturing Audio File**

This section of the code focuses on providing a user interface that allows for audio recordings to be sampled from the computer. The audio sample is then saved into a directory known as "audio_samples", which is referenced in later sections of the code.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install ffmpeg-python pydub ipywidgets

import IPython.display as display
import ipywidgets as widgets
import pydub
import os
import shutil

from pydub.playback import play
from google.colab import output
from base64 import b64decode

# Configure paths
output_folder = "audio_samples"
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

# Helper function to decode and save audio
def save_audio(b64_audio, filename):
    audio_data = b64decode(b64_audio.split(',')[1])
    with open(filename, "wb") as f:
        f.write(audio_data)

# Function to record audio using Colab's JS
def record_audio(filename):
    print("Click the 'Start Recording' button below, record your audio, and click 'Stop Recording' when finished.")
    display.display(widgets.HTML("""
    <script>
        var audioRecorder;
        var audioChunks;
        var startButton = document.createElement('button');
        var stopButton = document.createElement('button');

        startButton.textContent = 'Start Recording';
        stopButton.textContent = 'Stop Recording';

        startButton.style.padding = '10px';
        stopButton.style.padding = '10px';
        stopButton.style.marginLeft = '10px';

        document.body.appendChild(startButton);
        document.body.appendChild(stopButton);

        startButton.onclick = async function() {
            audioChunks = [];
            const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
            audioRecorder = new MediaRecorder(stream);
            audioRecorder.ondataavailable = e => audioChunks.push(e.data);
            audioRecorder.start();
        }

        stopButton.onclick = function() {
            audioRecorder.stop();
            audioRecorder.onstop = async function() {
                const blob = new Blob(audioChunks, { type: 'audio/wav' });
                const audioUrl = URL.createObjectURL(blob);
                const audio = new Audio(audioUrl);
                audio.play();
                var reader = new FileReader();
                reader.readAsDataURL(blob);
                reader.onloadend = function() {
                    google.colab.kernel.invokeFunction('notebook.save_audio', [reader.result], {});
                }
            }
        }
    </script>
    """))

# Callback to save audio
def handle_audio(b64_audio):
    save_audio(b64_audio, os.path.join(output_folder, "recording.wav"))
    print(f"Audio saved as recording.wav in {output_folder}")

# Bind the JavaScript callback
output.register_callback('notebook.save_audio', handle_audio)

# UI for audio recording
record_audio("recording.wav")

"""# **Loading Model for Automatic Speech Recognition**

This section of the code focuses on importing the wav2vec2 model from the Hugging Face Transformer Library through PyTorch. The audio received from the previous section of code is then resampled to 16000 Hz and funneled into the pretrained wave2vec2 model that is able to provide a predictive transcription of the audio.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install transformers torchaudio

from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
import torch
import torchaudio

# Step 2: Load Pre-trained Wave2Vec2.0 Model and Processor
model_name = "facebook/wav2vec2-base-960h"  # You can replace this with a different model
processor = Wav2Vec2Processor.from_pretrained(model_name)
model = Wav2Vec2ForCTC.from_pretrained(model_name)

# Step 3: Load and Process Audio File
def load_audio(file_path, target_sampling_rate=16000):
    # Load the audio file
    waveform, sample_rate = torchaudio.load(file_path)
    # Resample if necessary
    if sample_rate != target_sampling_rate:
        resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=target_sampling_rate)
        waveform = resampler(waveform)
    # Convert to single channel (mono) if needed
    if waveform.shape[0] > 1:
        waveform = torch.mean(waveform, dim=0, keepdim=True)
    return waveform.squeeze(), target_sampling_rate

audio_file = "audio_samples/recording.wav"  # Path to your recorded audio
waveform, sample_rate = load_audio(audio_file)

# Step 4: Tokenize the Audio
input_values = processor(waveform, sampling_rate=sample_rate, return_tensors="pt", padding=True).input_values

# Step 5: Perform Inference
with torch.no_grad():
    logits = model(input_values).logits

# Step 6: Decode the Prediction
predicted_ids = torch.argmax(logits, dim=-1)
transcription = processor.batch_decode(predicted_ids)[0]

# Step 7: Print the Transcription
print("Transcription:", transcription)

"""# **Phoneme Extraction using Model**

This section of the code focuses on transcribing the English text that is received from the pretrained model into individual phonemes. The phonemes are referenced from the International Phonetic Alphabet and provides accurate mapping of each word's pronounciation.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install phonemizer
# !apt-get update && apt-get install -y espeak

from phonemizer import phonemize

# Step 1: Transcribe Audio (Transcripition variable)

# Step 2: Convert Transcription to Phonemes
def transcribe_to_phonemes(text, language="en-us"):
    phonemes = phonemize(text, language=language, backend="espeak", strip=True)
    return phonemes

# Step 3: Phoneme Transcription
predictedPhoneme_transcription = transcribe_to_phonemes(transcription)
print("Predicted Phoneme Transcription:", predictedPhoneme_transcription)

"""# **Phoneme Alignment & Error Detection**

In this section of the code, the correct transcription of the intended pronounciation is translated into IPA format, and aligned with the predicted pronounciation to determine phonetic accuracy.

TO-DO:
1. Figure out what I need to test the children on based on the Goldman Fristoe Test of Articulation (Every words)
2. Ensure that the correct words are replaced as the "correct pronounciation" variable
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install jiwer torchaudio phonemizer

import torchaudio
import torch
from transformers import Wav2Vec2Processor, Wav2Vec2ForCTC
from phonemizer import phonemize
from jiwer import wer, cer
import numpy as np

# Convert correct transcription to phonemes
correct_transcription = "damn"  # Replace with the intended transcription
correct_phonemes = phonemize(correct_transcription, language="en-us", backend="espeak", strip=True)
print("Correct Phonemes:", correct_phonemes)

# Align the predicted and correct phonemes
def align_phonemes(predicted, correct):
    # Split both the predicted and correct phonemes into lists
    predicted_split = predicted.split()  # A list of phonemes in predicted transcription
    correct_split = correct.split()      # A list of phonemes in correct transcription

    # Initialize an empty alignment list
    alignment = []

    # Align the predicted phonemes with correct phonemes
    i, j = 0, 0
    while i < len(predicted_split) and j < len(correct_split):
        print(predicted_split[i], correct_split[j])
        if predicted_split[i] == correct_split[j]:
            alignment.append((correct_split[j], "correct"))
            i += 1
            j += 1
        else:
            alignment.append((predicted_split[i], "incorrect"))
            i += 1
    while i < len(predicted_split):
        alignment.append((predicted_split[i], "incorrect"))
        i += 1
    return alignment

alignment = align_phonemes(predictedPhoneme_transcription, correct_phonemes)
print("Phoneme Alignment:", alignment)

# Phoneme-level Alignment and Time Frame Assignment
def phoneme_time_frames(logits, audio_duration, predicted_phonemes):
    phonemes = predicted_phonemes.split()  # Split predicted transcription into phonemes
    time_per_token = audio_duration / logits.shape[1]  # Calculate time per token (frame)
    phoneme_times = []

    # Align phonemes with time frames
    for idx, phoneme in enumerate(phonemes):
        start_time = idx * time_per_token
        end_time = (idx + 1) * time_per_token
        phoneme_times.append((phoneme, start_time, end_time))
    return phoneme_times

audio_duration = waveform.shape[0] / sample_rate
phoneme_times = phoneme_time_frames(logits, audio_duration, predictedPhoneme_transcription)

# Identify incorrect phoneme time frames
incorrect_phoneme_times = [
    (phoneme, start, end)
    for (phoneme, status), (phoneme, start, end) in zip(alignment, phoneme_times)
    if status == "incorrect"
]

print("Incorrect Phoneme Time Frames:", incorrect_phoneme_times)

print("Predicted Phonemes:", predictedPhoneme_transcription)
print("Correct Phonemes:", correct_phonemes)
print("Phoneme Alignment:", alignment)
print("Incorrect Phoneme Time Frames:", incorrect_phoneme_times)

"""# **Accuracy of Phonetic Pronounciation**

1. Accuracy of all individual phonemes (Print N/A if not spoken)
2. Overall accuracy (correctly pronounced phonemes/all phonemes)
3. Word Error Rate (Subsitutions + Deletions + Insertions)/(Number of words in the Original Sentence)
"""

!pip install jiwer

#predictedPhoneme_transcription, correct_phonemes
print(predictedPhoneme_transcription)
print(correct_phonemes)

import jiwer
transforms = jiwer.Compose(
    [
        jiwer.ExpandCommonEnglishContractions(),
        jiwer.RemoveEmptyStrings(),
        jiwer.ToLowerCase(),
        jiwer.RemoveMultipleSpaces(),
        jiwer.Strip(),
        jiwer.RemovePunctuation(),
        jiwer.ReduceToListOfListOfWords(),
    ]
)

wer = jiwer.wer(
                predictedPhoneme_transcription,
                correct_phonemes,
                truth_transform=transforms,
                hypothesis_transform=transforms,
            )
print(f"Word Error Rate (WER) : " + str(wer*100) + "%")
print(f"Word Accuracy : " + str((1-wer)*100) + "%")